### ISSUE TITLE
Ellipsis in `out:` section leads to IndexError

### ISSUE THREAD

**Issue by aghast** [typeddjango/pytest-mypy-plugins#38]
Running Debian linux 10.5 with Python 3.8.0b4, this test case:
```
# typesafety/test_ellipsis.yml
- case: test_out_section_containing_ellipsis
  main: |
    reveal_type(int("1"))
  out: |
    ...
    main:1: note: Revealed type is 'builtins.int'

```
Produces this error:
```
$ pytest typesafety/test_ellipsis.yml 
==================================================== test session starts =====================================================
platform linux -- Python 3.8.0b4, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/aghast/Code/aghast/aghast-utils, configfile: pyproject.toml
plugins: cov-2.10.1, mypy-plugins-1.4.0
collected 1 item                                                                                                             

typesafety/test_ellipsis.yml F                                                                                         [100%]

========================================================== FAILURES ==========================================================
____________________________________________ test_out_section_containing_ellipsis ____________________________________________
Traceback (most recent call last):
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/_pytest/runner.py", line 294, in from_call
    result = func()  # type: Optional[_T]
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/_pytest/runner.py", line 247, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/_pytest/runner.py", line 161, in pytest_runtest_call
    raise e
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/_pytest/runner.py", line 153, in pytest_runtest_call
    item.runtest()
  File "/home/aghast/.pyenv/versions/3.8.0b4/envs/venv38/lib/python3.8/site-packages/pytest_mypy_plugins/item.py", line 253, in runtest
    assert_string_arrays_equal(expected=self.expected_output_lines, actual=output_lines)
  File "/home/aghast/.pyenv/versions/venv38/lib/python3.8/site-packages/pytest_mypy_plugins/utils.py", line 256, in assert_string_arrays_equal
    lineno = int(first_failure.split(" ")[0].strip(":").split(":")[1])
IndexError: list index out of range
================================================== short test summary info ===================================================
FAILED typesafety/test_ellipsis.yml::test_out_section_containing_ellipsis - IndexError: list index out of range

```

**Comment by sobolevn** [comment]
Yes, that's correct. `out` is designed to contain structured text. It fails on any other inputs.
